var getUrl=window.location;var baseUrl=window.location.origin;var homeText="Roblox Scripts - Rscripts, The #1 Free Roblox Script Provider!";var trendingText="Trending - Find the best, trending Roblox Scripts of this month!";var popularText="Popular - Find the most popular Roblox Scripts of the past 3 months!";window.onpopstate=function(event){if(window.location.href.indexOf("/script")>-1){removeNavActive();loadScript();loadScriptAds(2);loadTitle();scriptLoaderButton();$(".modal-backdrop").removeClass("modal-backdrop");$("body").css({"overflow":"visible"});}else if(window.location.href.indexOf("/trending")>-1){removeNavActive();loadTrending();loadScriptAds(1);}else if(window.location.href.indexOf("/popular")>-1){removeNavActive();loadPopular();loadScriptAds(1);}else{removeNavActive();loadContent();loadScriptAds(3);}};$("#home").on("click",function(){removeNavActive();loadContent();window.history.pushState("home","homeUrl",baseUrl.concat("/"));loadScriptAds(3);})
$("#trending").on("click",function(){removeNavActive();loadTrending();window.history.pushState("trending","trending",baseUrl.concat("/trending"));loadScriptAds(1);})
$("#popular").on("click",function(){removeNavActive();loadPopular();window.history.pushState("popular","popular",baseUrl.concat("/popular"));loadScriptAds(1);})
function removeNavActive(){$(".nav-item").removeClass("active");}
function loadScript(){NProgress.start();$("#main-page").empty();$("#main-page").load(baseUrl.concat("/script/script.php #main-page > *"))
waitForElm('#scriptframe').then((elm)=>{document.title=$("#title");var url=window.location.href
var id=url.split("-").pop()
$.ajax({url:baseUrl.concat("/scriptReceive.php"),method:"POST",data:{id:id},cache:false,success:function(data){var divs=data.split('----');$('#scriptframe').hide().html(divs[0]).fadeIn('slow');;$('#features').hide().html(divs[1]).fadeIn('slow');$('#download').hide().attr("href",(divs[2])).fadeIn('slow');if(data!==''){document.title=$("#title").html().concat(" - Roblox Scripts");$('meta[name=description]').attr('content',$("#description").html());scriptButton();$("#modalTitle").text($("#title").text());NProgress.done();}else{}}});})}
var limit=15;var start=0;$(document).on("click",".result .resultList .content h6",function(){$(this).parents(".search-box").find('input[type="text"]').val($(this).text());$(this).parent(".result").empty();});if(window.location.href.indexOf("/script")>-1){loadScriptAds(2);loadCaptcha();scriptButton();loadTitle();}
else if(window.location.href.indexOf("/trending")>-1){loadTrending();loadScriptAds(1);}else if(window.location.href.indexOf("/popular")>-1){loadPopular();loadScriptAds(1);}else{loadContent();loadScriptAds(3);}
function loadTrending(){NProgress.start();$("#main-page").empty();$("#main-page").load(baseUrl.concat("/trending.html #main-page > *"))
document.title=trendingText;waitForElm('#scriptgrid').then((elm)=>{$("#trending").parent().addClass("active")
$("#spinner").show();$.ajax({url:"trending.php",method:"POST",cache:false,success:function(data){var item=$(data).hide();$('#scriptgrid').append(item);item.fadeIn(500);if(data!==''){action='active';NProgress.done();}else{alert("Something went wrong, we're sorry!");NProgress.start();}
$("#spinner").hide();}})})}
function loadPopular(){NProgress.start();$("#main-page").empty();$("#main-page").load(baseUrl.concat("/popular.html #main-page > *"))
document.title=popularText;waitForElm('#scriptgrid').then((elm)=>{$("#popular").parent().addClass("active")
$("#spinner").show();$.ajax({url:"popular.php",method:"POST",cache:false,success:function(data){var item=$(data).hide();$('#scriptgrid').append(item);item.fadeIn(500);if(data!==''){action='active';NProgress.done();}else{alert("Something went wrong, we're sorry!");}
$("#spinner").hide();}})})}
function loadContent(){$("#main-page").empty();$("#main-page").load(baseUrl.concat("/index.html #main-page > *"))
document.title=homeText;waitForElm('#scriptgrid').then((elm)=>{var data=localStorage.getItem("patched");if(data=="true"){$("#switch_show").prop("checked",true);}
$("#switch_show").prop('checked',data=='true').change(function(){localStorage.patched=$(this).prop("checked");$("#scriptgrid").empty();var url_string=window.location.href
var url=new URL(url_string);var c=url.searchParams.get("q");if(c){loadScriptsSearch(15,0,c)}else{loadScripts(15,0);}});$("#home").parent().addClass("active")
$('#filter').change(function(){$("#scriptgrid").empty();var url_string=window.location.href
var url=new URL(url_string);var c=url.searchParams.get("q");if(c){loadScriptsSearch(15,0,c)}else{loadScripts(15,0);}});var limit=15;var start=0;var button=$('#loadMore');function disableButton(){button.text("No More Data Found");button.removeClass("btn-primary");button.removeClass("shadow-primary");button.addClass("btn-danger");button.prop("disabled",true);}
function enableButton(){button.text("Show More");button.removeClass("btn-danger");button.addClass("btn-primary");button.addClass("shadow-primary");button.prop("disabled",false);}
$("#filter").change(function(){var selected=$(this).val();setQueryStringParameter("filter",selected);});var url_string=window.location.href
var url=new URL(url_string);var c=url.searchParams.get("filter");if(filter){$('#filter option[value='.concat(c).concat(']')).attr('selected','selected');}
function loadScripts(limit,start){$("#loadMore").text("Loading...");var hidePatched=0;var filter=$('#filter option:selected').val();if($('#switch_show').is(':checked')){var hidePatched=1;}
$("#spinner").show();NProgress.start();$.ajax({url:baseUrl.concat("/backend.php?v=1.2"),method:"POST",data:{limit:limit,start:start,patched:hidePatched,filter:filter},cache:false,success:function(data){var item=$(data).hide();$('#scriptgrid').append(item);item.fadeIn(500);if(start<8&&data!==''){action='active';enableButton();NProgress.done();}else if(data=='000'){disableButton();action='active';NProgress.done();}else{enableButton();action="active";NProgress.done();}
$("#spinner").hide();}});}
function loadScriptsSearch(limit,start,term){NProgress.start();$("#loadMore").text("Loading...");var hidePatched=0;var filter=$('#filter option:selected').val();if($('#switch_show').is(':checked')){var hidePatched=1;}
$('#spinner').show();$.ajax({url:"backend.php?v=1.2",method:"POST",data:{limit:limit,start:start,search:term,patched:hidePatched,filter:filter},cache:false,success:function(data){var item=$(data).hide();$('#scriptgrid').append(item);item.fadeIn(500);if(start<8&&data!=='000'){action='active';enableButton();NProgress.done();}else if(data=='000'){disableButton();action='active';NProgress.done();}else{enableButton();action="active";NProgress.done();}
$('#spinner').hide();}});}
var url_string=window.location.href
var url=new URL(url_string);var c=url.searchParams.get("q");if(c){loadScriptsSearch(limit,start,c)
searchModifier()
$("#searchBar").val(c)}else{loadScripts(limit,start);}
$("#loadMore").on('click',function(){action='active';start=start+limit;if(window.location.href.indexOf("?q")){var url_string=window.location.href
var url=new URL(url_string);var c=url.searchParams.get("q");$('#spinner').show();loadScriptsSearch(limit,start,c)
$('#spinner').hide();}else{$('#spinner').show();loadScripts(limit,start);$('#spinner').hide();}})
function searchModifier(){$(".titlePage").remove();$(".descriptionPage").remove();$("#searchHolder").removeClass("mt-20");$("#searchHolder").addClass("mt-15");$(".headerBox").removeClass("vh-100");$(".headerBox").height("30vh");$("#sbox").removeClass("mb-5");$("#sbox").css("bottom","10vh");$("#scriptScroller").remove();window.scrollTo({top:0,behavior:'smooth'});}
$("#searchBar").on("focus",function(){$('.result').on('mousedown',function(event){event.preventDefault();});searchModifier()
var inputVal=$(this).val();var resultDropdown=$(this).siblings(".result");if(inputVal.length){$.get("ajaxSearch.php?v=1.1",{term:inputVal}).done(function(data){resultDropdown.html(data);});}else{resultDropdown.empty();}})
$("#searchBar").on("keyup",function(e){NProgress.start()
$('.result').on('mousedown',function(event){event.preventDefault();});var that=this,value=$(this).val();if(e.which<=90&&e.which>=48||e.which===8||e.which===16||e.which===17){if(value==""&&e.which!==17&&e.which!==16){$("#scriptgrid").empty();setQueryStringParameter("q","");loadScripts(15,0)}else{setQueryStringParameter("q",value);}
var inputVal=$(this).val();var resultDropdown=$(this).siblings(".result");if(inputVal.length){$.get("ajaxSearch.php",{term:inputVal}).done(function(data){resultDropdown.html(data);NProgress.done()});}else{resultDropdown.empty();}}})
$("#clearButton").on("click",function(){$('#searchBar').val('')
$("#scriptgrid").empty();setQueryStringParameter("q","");loadScripts(15,0)})
$("#searchButton").on("click",function(){startSearch();})
function startSearch(){document.querySelectorAll('.resultList').forEach(e=>e.remove());start=0;action='active';$("#scriptgrid").empty();var url_string=window.location.href
var url=new URL(url_string);var c=url.searchParams.get("q");loadScriptsSearch(limit,start,c);}
$("#searchBar").on("focusout",function(){document.querySelectorAll('.resultList').forEach(e=>e.remove());})
$('#searchBar').on("keypress",function(e){if(e.which==13){startSearch();}});});}
function contentDisp(obj){NProgress.start();removeNavActive();var someurl=$(obj).attr("href");$("#main-page").load(someurl.concat(" #main-page > *"),function(){window.scrollTo(0,0);NProgress.done();window.history.pushState("script",someurl,someurl);$("#home").parent().removeClass("active");loadTitle();loadScriptAds(2);loadCaptcha()
scriptButton();})
return false;}
function loadTitle(){waitForElm('#scriptframe').then((elm)=>{document.title=$("#title").text();})}
function scriptLoaderButton(){waitForElm('#copyButton').then((elm)=>{$("#loadScript").one("click",function(){console.log("BOOGABOOGA");$("#copyButton").on("click",function(){$("textarea").select();document.execCommand('copy');$(this).text("✓ Copied");})
$("#waitForScript").toggle();var url=window.location.href
var id=url.split("-").pop()
$.ajax({url:baseUrl.concat("/getScript.php"),method:"POST",data:{id:id},cache:false,success:function(data){if(data!==""){$("#waitForScript").toggle();$("#scriptContent").text(data);$("#scriptContent").toggle();}else{alert("Something went wrong, please join our discord and reach out for help if the issue persists!");}}})})})}
function scriptButton(){waitForElm('#reportButton').then((elm)=>{jQuery.loadScript=function(url,callback){jQuery.ajax({url:url,dataType:'script',success:callback,async:true});}
if(typeof someObject=='undefined')$.loadScript('//d1nubxdgom3wqt.cloudfront.net/?xbund=958688',function(){});if(typeof someObject=='undefined')$.loadScript('https://rscripts.net/antiAsolution.js',function(){});loadCaptcha();scriptLoaderButton();$("#reportButton").on("click",function(){NProgress.start();$(this).prop("disabled",true);$(this).text("Loading...");var url=window.location.href
var id=url.split("-").pop()
var reason=$("#reason option:selected").text();var gresponse=grecaptcha.getResponse();if(gresponse.length>0){$.ajax({url:baseUrl.concat("/submitReport.php"),method:"POST",data:{reason:reason,id:id,response:gresponse},cache:false,success:function(data){if(data=="001"){$("#reportButton").removeClass("btn-danger");$("#reportButton").addClass("btn-success");$("#reportButton").text("Done, thank you!");NProgress.done();}else{$("#reportButton").prop("disabled",false);$("#reportButton").text("Try again");NProgress.done();}}})}else{$(this).prop("disabled",false);$(this).text("Please do the captcha!");}})})}
function loadCaptcha(){waitForElm('#reportButton').then((elm)=>{$("#mainReport").on("click",function(){if(!$.trim($('#captcha_container').html()).length){var siteKey='6Le2Z7MaAAAAAM2UgYd6OHv-oqJ_D3vYpPKqtWVI';grecaptcha.render('captcha_container',{'sitekey':siteKey});}})})}
function setQueryStringParameter(name,value){const params=new URLSearchParams(window.location.search);params.set(name,value);window.history.replaceState({},"",decodeURIComponent(`${window.location.pathname}?${params}`));}
function loadScriptAds(value){waitForElm('#scriptgrid').then((elm)=>{jQuery.loadScript=function(url,callback){jQuery.ajax({url:url,dataType:'script',success:callback,async:true});}
if(typeof someObject=='undefined')$.loadScript('https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2192724296802940',function(){if(value==2){$(".googleAd1").each(function(){$(this).append('<ins class="adsbygoogle responsiveAd" style="display:block" data-ad-client="ca-pub-2192724296802940" data-ad-slot="2260047238"></ins>');(adsbygoogle=window.adsbygoogle||[]).push({});});$(".googleAd3").each(function(){$(this).append('<ins class="adsbygoogle" style="display:inline-block;width:300px;height:250px" data-ad-client="ca-pub-2192724296802940" data-ad-slot="7018771086"></ins>');(adsbygoogle=window.adsbygoogle||[]).push({});});$(".googleAd4").each(function(){$(this).append('<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-2192724296802940" data-ad-slot="8794006270" data-ad-format="auto" data-full-width-responsive="true"></ins>');(adsbygoogle=window.adsbygoogle||[]).push({});});$(".googleAd5").each(function(){$(this).append('<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-2192724296802940" data-ad-slot="1273860161" data-ad-format="auto" data-full-width-responsive="true"></ins>');(adsbygoogle=window.adsbygoogle||[]).push({});});}else if(value==3){$(".googleAd3").each(function(){$(this).append('<ins class="adsbygoogle" style="display:inline-block;width:300px;height:250px" data-ad-client="ca-pub-2192724296802940" data-ad-slot="7018771086"></ins>');(adsbygoogle=window.adsbygoogle||[]).push({});});}else{$(".googleAd1").each(function(){$(this).append('<ins class="adsbygoogle responsiveAd" style="display:block" data-ad-client="ca-pub-2192724296802940" data-ad-slot="2260047238"></ins>');(adsbygoogle=window.adsbygoogle||[]).push({});});}});})}
function waitForElm(selector){return new Promise(resolve=>{if(document.querySelector(selector)){return resolve(document.querySelector(selector));}
const observer=new MutationObserver(mutations=>{if(document.querySelector(selector)){resolve(document.querySelector(selector));observer.disconnect();}});observer.observe(document.body,{childList:true,subtree:true});});}